version: '2'
services:
    foo-app:
        image: foo
        external_links:
            - foo-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=foo
            - JHIPSTER_SLEEP=10
            - SPRING_CLOUD_CONFIG_URI=http://admin:undefined@registry:8761/config
    foo-mongodb:
        container_name: foo-mongodb
        image: mongo:3.2.10
    
    gateway-app:
        image: gateway
        external_links:
            - gateway-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - SPRING_CLOUD_CONFIG_URI=http://admin:undefined@registry:8761/config
        ports:
            - 8080:8080
    gateway-mongodb-node:
        build:
            context: ../gateway/src/main/docker
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    gateway-mongodb-config:
        image: mongo:3.2.10
        container_name: gateway-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
    gateway-mongodb:
        container_name: gateway-mongodb
        image: mongo:3.2.10
        command: mongos --configdb gateway-mongodb-config
    
    consul:
        extends:
            file: consul.yml
            service: consul
    consul-config-loader:
        extends:
            file: consul.yml
            service: consul-config-loader

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console

